"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INCREMENT_SKIPPED = exports.INCREMENT_SOLVED = exports.SET_DIFFICULTY_NORMAL = exports.SET_DIFFICULTY_HARD = exports.INITIALIZE_SESSION = void 0;
exports.INITIALIZE_SESSION = "INITIALIZE_SESSION";
exports.SET_DIFFICULTY_HARD = "SET_DIFFICULTY_HARD";
exports.SET_DIFFICULTY_NORMAL = "SET_DIFFICULTY_NORMAL";
exports.INCREMENT_SOLVED = "INCREMENT_SOLVED";
exports.INCREMENT_SKIPPED = "INCREMENT_SKIPPED";
