export const INITIALIZE_SESSION = "INITIALIZE_SESSION";
export const SET_DIFFICULTY_HARD = "SET_DIFFICULTY_HARD";
export const SET_DIFFICULTY_NORMAL = "SET_DIFFICULTY_NORMAL";
export const INCREMENT_SOLVED = "INCREMENT_SOLVED";
export const INCREMENT_ATTEMPTED = "INCREMENT_ATTEMPTED";